insert into estados values("1","AC","Acre");
insert into estados values("2","AL","Alagoas");
insert into estados values("3","AM","Amazonas");
insert into estados values("4","AP","Amapá");
insert into estados values("5","BA","Bahia");
insert into estados values("6","CE","Ceará");
insert into estados values("7","DF","Distrito Federal");
insert into estados values("8","ES","Espírito Santo");
insert into estados values("9","GO","Goiás");
insert into estados values("10","MA","Maranhão");
insert into estados values("11","MG","Minas Gerais");
insert into estados values("12","MS","Mato Grosso do Sul");
insert into estados values("13","MT","Mato Grosso");
insert into estados values("14","PA","Pará");
insert into estados values("15","PB","Paraíba");
insert into estados values("16","PE","Pernambuco");
insert into estados values("17","PI","Piauí");
insert into estados values("18","PR","Paraná");
insert into estados values("19","RJ","Rio de Janeiro");
insert into estados values("20","RN","Rio Grande do Norte");
insert into estados values("21","RO","Rondônia");
insert into estados values("22","RR","Roraima");
insert into estados values("23","RS","Rio Grande do Sul");
insert into estados values("24","SC","Santa Catarina");
insert into estados values("25","SE","Sergipe");
insert into estados values("26","SP","São Paulo");
insert into estados values("27","TO","Tocantins");
